spring:
  application:
    name: warehouse
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6434/warehouse
    username: dbuser
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR