spring:
  application:
    name: aggregator

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

aggregator:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "telemetry.aggregator"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        snapshots-events: telemetry.snapshots.v1
    consumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: aggregator-group
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
        auto.offset.reset: earliest
        enable.auto.commit: false
      topics:
        sensors-events: telemetry.sensors.v1